### ISSUE TITLE
LISTA DE EXERCICIOS 1

### ISSUE THREAD

**Issue by gpessoni** [dfpires/poo-noite-2022-2#1]
Olá professor.
Foi dito na última aula que seria passado uma lista com três exercicios, contúdo foi colocado no repositório um arquivo com 25 exercicios do livro "Fundamentos da Programação de computadores Assencio Campos". O arquivo está correto mesmo ?

**Comment by dfpires** [comment]
Oi Gabriel,

Fiz a alteração, obrigado por avisar.

Daniel

**Comment by gpessoni** [comment]
Eu que agradeço professor
Irei fechar a issue.
